### ISSUE TITLE
Error message at run

### ISSUE THREAD

**Issue by imTHAI** [gespinal/utilz#1]
Hello,

When I try to run the App I get this error message:
![Capture d’écran 2020-04-13 à 08 57 18](https://user-images.githubusercontent.com/36070606/79099650-ed520b00-7d64-11ea-95bb-997ef901f8a7.png)

During the process of the shell script, after it finishes to download both dmg, there are 2 errors about sed commands:

```
> Extracting the 32-bit app from YNAB4_LiveCaptive_4.3.855.dmg
"disk3" ejected.
> Extracting the 64-bit Adobe AIR runtime from AdobeAIR.dmg
"disk3" ejected.
> Converting the 32-bit app to a native 64-bit app
sed: can't read s/MacOS-x86/MacOS-x86-64/: No such file or directory
sed: can't read s/MacOS-x86/MacOS-x86-64/: No such file or directory
==========================================================
                   _                  _
                  | |                | |
                __| | ___  _ __   ___| |
               / _  |/ _ \|  _ \ / _ \ |
              | (_| | (_) | | | |  __/_|
               \__,_|\___/|_| |_|\___(_)
==========================================================
> The app 'YNAB 4.app' has been saved to:
> "/var/folders/q9/tcb9s5856j190_zpqb2y253h0000gn/T/tmp.cKjyt6QQ"
> Drag the app to your /Applications directory to install
==========================================================
Press [ENTER] to open the folder containing the app
> Done!
```

**Comment by gespinal** [comment]
Hello,

I'm unable to try and test right now, but feel free to download the x86-64 version from this link:

https://drive.google.com/file/d/1nKWyEfh9CW-sYZCDlJWhCB4K5-titWL9/view?usp=sharing

Just unpack and move to Applications.

Best regards...

**Comment by imTHAI** [comment]
Thanks. Since then, I subscribed to nYnab. But I don't really see any useful improvement from the YNAB4 app. I may come back to the app.

**Comment by gespinal** [comment]
Glad to help... I tried a 4 month trial of nYnab and it didn't work for me. I'm also sticking to YNAB4, at least for now.
